const number = 5.5;

const absValue = Math.abs(number);
const roundedValue = Math.round(number);
const ceilValue = Math.ceil(number);
const floorValue = Math.floor(number);
const squareRoot = Math.sqrt(25);
const cubicRoot = Math.cbrt(27);
const powerValue = Math.pow(2, 3);
const exponentialValue = Math.exp(1);
const logValue = Math.log(10);
const log10Value = Math.log10(100);
const sineValue = Math.sin(Math.PI / 2);
const cosineValue = Math.cos(0);
const tangentValue = Math.tan(Math.PI / 4);
const minValue = Math.min(10, 20, -5, 0, 100);
const maxValue = Math.max(10, 20, -5, 0, 100);
const randomValue = Math.random();
const randomInRange = Math.floor(Math.random() * 10) + 1;
const truncValue = Math.trunc(4.9);
const signValue = Math.sign(-5);

console.log(absValue);
console.log(roundedValue);
console.log(ceilValue);
console.log(floorValue);
console.log(squareRoot);
console.log(cubicRoot);
console.log(powerValue);
console.log(exponentialValue);
console.log(logValue);
console.log(log10Value);
console.log(sineValue);
console.log(cosineValue);
console.log(tangentValue);
console.log(minValue);
console.log(maxValue);
console.log(randomValue);
console.log(randomInRange);
console.log(truncValue);
console.log(signValue);
