const str = "Hello, World!";

const length = str.length;
const lowerCase = str.toLowerCase();
const upperCase = str.toUpperCase();
const charAtIndex = str.charAt(7);
const charCodeAt = str.charCodeAt(7);
const indexOfSubstring = str.indexOf('World');
const lastIndexOfSubstring = str.lastIndexOf('o');
const startsWithHello = str.startsWith('Hello');
const endsWithWorld = str.endsWith('World!');
const includesWorld = str.includes('World');
const substring = str.substring(7, 12);
const slice = str.slice(7, 12);
const splitString = str.split(', ');
const replaceSubstring = str.replace('World', 'JavaScript');
const trimString = "  Hello, World!  ".trim();
const repeatString = str.repeat(2);
const concatString = str.concat(' How are you?');
const padStartString = str.padStart(20, '*');
const padEndString = str.padEnd(20, '*');

console.log(length);
console.log(lowerCase);
console.log(upperCase);
console.log(charAtIndex);
console.log(charCodeAt);
console.log(indexOfSubstring);
console.log(lastIndexOfSubstring);
console.log(startsWithHello);
console.log(endsWithWorld);
console.log(includesWorld);
console.log(substring);
console.log(slice);
console.log(splitString);
console.log(replaceSubstring);
console.log(trimString);
console.log(repeatString);
console.log(concatString);
console.log(padStartString);
console.log(padEndString);
